#!/bin/sh

cat << "EOF"
 _                   _ _____     _____     _____
| |_ ___ ___ ___ ___| |   __|___| __  |_ _| __  |___
| '_| -_|  _|   | -_| |__   |  _|    -| | | __ -|_ -|
|_,_|___|_| |_|_|___|_|_____|___|__|__|___|_____|___|

EOF

echo ">> Please be patient we are polling this port. Delays may occur..."
echo ">> Starting remote shell."
nc $1 -lv 2000